outer_region:
  fast:
    points:
      - x: 1.0
        y: 0.6

      - x: 1.8
        y: 0.4

      - x: 1.8
        y: -0.4

      - x: 1.0
        y: -0.6

      - x: -1.0
        y: -0.6

      - x: -1.0
        y: 0.6

  slow:
    points:
      - x: 1.0
        y: 0.6

      - x: 1.0
        y: -0.6

      - x: -0.8
        y: -0.6

      - x: -0.8
        y: 0.6

inner_region:
  points:
    - x: 0.5
      y: 0.6

    - x: 0.5
      y: -0.6

    - x: -0.3
      y: -0.6

    - x: -0.3
      y: 0.6

front_region:
  points:
    - x: 1.0
      y: 0.6

    - x: 1.0
      y: -0.6

    - x: 0.5
      y: -0.6

    - x: 0.5
      y: 0.6

rear_region:
  points:
    - x: -0.8
      y: 0.6

    - x: -0.8
      y: -0.6

    - x: -0.3
      y: -0.6

    - x: -0.3
      y: 0.6

